kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: alpine
    environment:
      SERVER_HOST: ${DRONE_SERVER_HOST} # Ensure this is set correctly
    commands:
      - echo "Building project..."
