kind: pipeline
type: docker
name: test-pipeline
#
steps:
  - name: test
    image: alpine
    commands:
      - echo "Starting tests..."
      - uname -a   # Outputs system information to confirm the runner
      - echo "Tests completed."
