---
kind: pipeline
type: docker
name: hello-world

platform:
  os: linux
  arch: arm64

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: joselara9/hello-world
    username:
     from_secret: docker_username
    password:
     from_secret: docker_password
    tags:
     - latest
