/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./components/Avatar.vue')['default']
    Container: typeof import('./components/Container.vue')['default']
    DesktopNav: typeof import('./components/DesktopNav.vue')['default']
    Experience: typeof import('./components/Experience.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    InnerContainer: typeof import('./components/InnerContainer.vue')['default']
    MobileNav: typeof import('./components/MobileNav.vue')['default']
    NavItem: typeof import('./components/NavItem.vue')['default']
    OuterContainer: typeof import('./components/OuterContainer.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Showcase: typeof import('./components/Showcase.vue')['default']
    Socials: typeof import('./components/Socials.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    WorkExperiences: typeof import('./components/WorkExperiences.vue')['default']
  }
}
